lesson4/geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = "authapp"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),

]

lesson4/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from geekshop.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace="products"), name="products"),
    path('auth/', include('authapp.urls', namespace="auth"), name="auth"),
    path('contacts/', contacts, name="contacts"),
    path('', index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson4/geekshop/mainapp/urls.py
from django.urls import path
from .views import index

app_name = "mainapp"

urlpatterns = [
    path('', index, name="index"),
]

lesson4/geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

lesson4/geekshop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='название продукта',
        max_length=128,
    )
    short_desc = models.CharField(
        max_length=256,
        blank=True,
        verbose_name='краткое описание',
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    def __str__(self):
        return f'{self.name} - {self.pk}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

lesson4/geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

        def __init__(self, *args, **kwargs):
            super(ShopUserLoginForm, self).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'

class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name','password1', 'password2', 'email', 'age', 'avatar')

        def __init__(self, *args, **kwargs):
            super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')
        return data

    def clean_email(self):
        data = self.cleaned_data['email']
        if data.find("crimea.ru") != -1:
            raise forms.ValidationError('Мы не регистрируем пользователей из Крыма')
        return data

class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        data = self.cleaned_data['age']

        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')
        return data
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if data.find("crimea.ru") != -1:
            raise forms.ValidationError('Мы не регистрируем пользователей из Крыма')
        return data

lesson4/geekshop/authapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import auth
from django.urls import reverse

from .forms import ShopUserLoginForm, ShopUserEditForm, ShopUserRegisterForm


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    context = {
        'title': title,
        'login_form': login_form,
    }

    return render(request, 'authapp/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form,
    }

    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование профиля'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'title': title,
        'edit_form': edit_form
    }

    return render(request, 'authapp/edit.html', context)

lesson4/geekshop/geekshop/views.py
from django.shortcuts import render
from datetime import date

def index(request):
    context = {
        'slogan':'Супер предложения',
        'time' : date.today()
    }
    return render(request, 'geekshop/index.html', context)

def contacts(request):
    return render(request, 'geekshop/contact.html')

lesson4/geekshop/mainapp/views.py
from django.shortcuts import render
import json

from mainapp.models import Product

from mainapp.models import ProductCategory


def index(request):
    title = 'каталог'

    # with open('mainapp/templates/mainapp/links_menu.json') as f:
    #     links_menu = json.load(f)
    links_menu = ProductCategory.objects.all()

    products = Product.objects.all()[0:3]

    context = {
        'title': title,
        'links_menu': links_menu,
        'related_products': products
    }
    return render(request, 'mainapp/products.html', context)

lesson4/geekshop/authapp/templates/authapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}{{title|title}}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	<div class="container">
        {% include 'geekshop/includes/inc_main_menu.html'%}

        {% block content %}
        {% endblock %}

    	<div class="clr"></div>

    </div>
</body>
</html>

lesson4/geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-4 mx-auto">
        <div class="row">
            <div class="user_avatar">
                <img src="/media/{{ user.avatar }}" class="rounded-circle">
            </div>
        </div>
    <div class="row">
        <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'index' %}" class="">
                на главную
            </a>
        </button>
    </div>
    </div>
{% endblock %}

lesson4/geekshop/authapp/templates/authapp/login.html
{{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="mx-auto col-3">
                <form class="form-horizontal" action="{% url 'auth:login' %}" method="post" >
                    {% csrf_token %}
                    {{ login_form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
        </div>
        <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
    </div>
{% endblock %}

lesson4/geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Зарегистрироваться">
    </form>
    </div>
{% endblock %}

lesson4/geekshop/geekshop/templates/geekshop/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}{{title|title}}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
	<link rel="stylesheet" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
</head>
<body>
	<div class="container">
        {% include 'geekshop/includes/inc_main_menu.html'%}

        {% block content %}
        {% endblock %}

	<div class="clr"></div>

</div>


    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

lesson4/geekshop/geekshop/templates/geekshop/contact.html
{% extends "geekshop/base.html" %}
{% load static %}

{% block content %}

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

lesson4/geekshop/geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="active">домой</a></li>
        <li><a href="{% url 'products:index' %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
              <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
              <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>


    </ul>
    <a href="#" class="search"></a>
</div>

lesson4/geekshop/geekshop/templates/geekshop/index.html
{% extends "geekshop/base.html" %}
{% load static %}
{% block content %}
<div class="slider">
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<h4>Только {{ time }} {{ slogan | title }}</h4>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
	</div>
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>


<div class="featured">
	<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		<div class="block">
			<a href="#"><img src="{% static 'geekshop/img/product-1.jpg' %}" alt="">
				<div class="text">
					<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
					<h4>Отличный стул</h4>
					<p>Расположитесь комфортно. </p>
				</div>
			</a>
		</div>
		<div class="block">
			<a href="#"><img src="{% static 'geekshop/img/product-2.jpg' %}" alt="">
				<div class="text">
					<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="">
					<h4>Стул повышенного качества</h4>
					<p>Не оторваться. </p>
				</div>
			</a>
		</div>
	</div>
</div>
{% endblock %}

lesson4/geekshop/mainapp/templates/mainapp/includes/inc_category_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        {% for link in links_menu %}
        <li><a href="#" class="{% if request.resolver_match.url_name == link.href %}active{% endif %}">{{link.name}}</a></li>
        {% endfor %}
    </ul>
</div>

lesson4/geekshop/mainapp/templates/mainapp/products.html
{% extends "geekshop/base.html" %}
{% load static %}

{% block content %}

<div class="details">
{% include 'mainapp/includes/inc_category_menu.html' %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{% static 'geekshop/img/slider1.jpg' %}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">Отличный стул</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> 2585.9 <span>руб</span></p>
			<a href="#" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>Расположитесь комфортно.</p>
				<p>Отличное качество материалов
				позволит вам это.</p>
				<p>Различные цвета</p>
				<p>высочайший уровень
				эргономики и прочность.</p>
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% for product in related_products %}
			<div class="block">
				<a href="#"><img src="/media/{{ product.image }}" alt="">
					<div class="text">
						<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
						<h4>{{ product.name }}</h4>
						<p>{{ product.short_description }}</p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}